name: CI

on:
  push:
    branches: [master]
    tags: ["*.*.*"]
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    name: Test suite
    runs-on: self-hosted
    container:
      image: registry.gitlab.inria.fr/catala/ci-images:latest-python
      options: --user root
    steps:
      - name: Fix home
        # Workaround Github actions issue, see
        # https://github.com/actions/runner/issues/863
        run: sudo sh -c "echo HOME=/home/ocaml >> ${GITHUB_ENV}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check formatting
        run: |
          opam --cli=2.1 exec -- make check-format
      - name: Install Java dependencies
        run: |
          apk add openjdk21
      - name: Run tests (interpreter and backends)
        run: |
          opam --cli=2.1 exec -- clerk ci
